import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Grab Quotes</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Grap Quotes</h1>
        <p>Grab Quotes is a website where you can grab quotes from your favorite movies and tv shows.</p>
      </main>
    </>
  );
}
